### ISSUE TITLE
Warnings/Errors after installing latest autolink2 version

### ISSUE THREAD

**Issue by joemouth** [oiv/autolink2#1]
Warning: Cannot modify header information - headers already sent by (output started at /...dw-path.../lib/plugins/autolink2/action.php:42) in /...dw-path.../inc/actions.php on line 180

Warning: preg_replace() [function.preg-replace]: Compilation failed: missing terminating ] for character class at offset 95 in /...dw-path.../lib/plugins/autolink2/action.php on line 42

do=check:

DokuWiki version: Release 2011-05-25a "Rincewind"
PHP version 5.3.8-1~dotdeb.1
More than 32MB RAM (268435456 bytes) available.
Changelog is writable
Datadir is writable
Attic is writable
Mediadir is writable
Cachedir is writable
Lockdir is writable
conf/users.auth.php is writable
mb_string extension is available and will be used
Debugging support is disabled
You are currently logged in as (Admin))
You are part of the groups admin, developer, poweruser, user
Your current permission for this page is 255
The current page is writable by the webserver
The current page is writable by you
Failed to check if the data directory is accessible from the web. Make sure this directory is properly protected (See security)
The search index seems to be working

**Comment by oiv** [comment]
Please check you /data/index/autolink.idx file. It may contain [ character which will mess the process. You have to remove that extra "[" from the autolink.idx file AND from the page where you have it set.

I will do a check for illegal character in the anchors for the next release.

**Comment by joemouth** [comment]
Thank so much for your fast response!
Now it works.
