### ISSUE TITLE
add noautolink feature for selected area of the DW page

### ISSUE THREAD

**Issue by joemouth** [oiv/autolink2#5]
I would like to use the automatic autolink feature which is great, but some parts of my DW page should be processed through autolink.

Could this be posssible?

eg.
  < noutolink >
  ...
  < /noautolink >

The reason is, that I use the plantuml plugin, which generates UML grafic diagramms from text.
If this text has autolink2 keywords they will be substituted with internal DW links, which makes no sense.

**Comment by oiv** [comment]
Yes. This should be possible.  However I am currently a bit busy. Will check this later...

**Comment by joemouth** [comment]
Please leave it still open until you find time to add this feature.

Thanks for your time and good work!
